# 

POST https://localhost:5001/api/signin
Content-Type: application/json

{
    "email": "root@root",
    "password": "Password123!"
}

POST https://localhost:5001/api/signup
Content-Type: application/json

{
    "email": "root1@root",
    "password": "Password123!"
}